### ISSUE TITLE
rts_wm_entry never handle any reuqest

### ISSUE THREAD

**Issue by adreyk** [rzezeski/try-try-try#2]
riak_core register webmachine before you and it do application:set_env(webmachine, dispatch_lis,....t) before you and this value never overides see webmachine_mochiweb.erl:
application_set_unless_env(App, Var, Value) ->
    Current = application:get_all_env(App),
    CurrentKeys = proplists:get_keys(Current),
    case lists:member(Var, CurrentKeys) of
        true ->
            ok;
        false ->
            application:set_env(App, Var, Value)
    end.

**Comment by rzezeski** [comment]
Hmmm, something might have changed recently.  I probably should have set the dependencies to a certain commit/tag instead of master.  I'll try to look at this soon.

**Comment by adreyk** [comment]
Yes u are right. In previous version function application_set_unless_env does't exists, application:set_env(App, Var, Value) called and override default riack_core dispather.

**Comment by rzezeski** [comment]
It turns out I shouldn't have been using this method at add my routes in the first place.  The appropriate way is to use the [add_route](https://github.com/basho/webmachine/blob/master/src/webmachine_router.erl) function.  I'm in the process of updating all my example code.  Thx for the report @adreyk.

**Comment by rzezeski** [comment]
Forgot about this issue...pretty sure I fixed all examples.
